name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make eXperimental!
        run: sh ./sh/helloworld.sh
        
      - name: Update files on GitHub
      - uses: test-room-7/action-update-file@v1.5.0
        with:
          file-path: experimental.txt
          commit-msg: "Experimental $update del $lastmodified"
          github-token: ${{ secrets.GHUB_TOKEN }}
